services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=fintechdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    container_name: fintech_postgres

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    container_name: fintech_redis

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'      # For app connection
      - '15672:15672'  # For management UI
    environment:
      - 'RABBITMQ_DEFAULT_PASS=password'
      - 'RABBITMQ_DEFAULT_USER=user'
    container_name: fintech_rabbitmq

